<?php

namespace ContainerJK49Jwz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4t3QSeCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4t3QSeC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4t3QSeC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'answer' => ['privates', '.errored..service_locator.4t3QSeC.App\\Entity\\Answers', NULL, 'Cannot autowire service ".service_locator.4t3QSeC": it references class "App\\Entity\\Answers" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'answer' => 'App\\Entity\\Answers',
            'entityManager' => '?',
        ]);
    }
}
