<?php

namespace ContainerJK49Jwz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UUPz_DKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uUPz.dK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uUPz.dK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'answer' => ['privates', '.errored..service_locator.uUPz.dK.App\\Entity\\Answers', NULL, 'Cannot autowire service ".service_locator.uUPz.dK": it references class "App\\Entity\\Answers" but no such service exists.'],
        ], [
            'answer' => 'App\\Entity\\Answers',
        ]);
    }
}
