<?php

namespace ContainerO5KUIo8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JpDh4PuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JpDh4Pu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JpDh4Pu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ticket' => ['privates', '.errored..service_locator.JpDh4Pu.App\\Entity\\Tickets', NULL, 'Cannot autowire service ".service_locator.JpDh4Pu": it references class "App\\Entity\\Tickets" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'ticket' => 'App\\Entity\\Tickets',
        ]);
    }
}
