<?php

namespace ContainerO5KUIo8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YJZ2AOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y_jZ2AO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y_jZ2AO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AnswersController::delete' => ['privates', '.service_locator.4t3QSeC', 'get_ServiceLocator_4t3QSeCService', true],
            'App\\Controller\\AnswersController::edit' => ['privates', '.service_locator.4t3QSeC', 'get_ServiceLocator_4t3QSeCService', true],
            'App\\Controller\\AnswersController::index' => ['privates', '.service_locator.Rl2KN_W', 'get_ServiceLocator_Rl2KNWService', true],
            'App\\Controller\\AnswersController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AnswersController::show' => ['privates', '.service_locator.uUPz.dK', 'get_ServiceLocator_UUPz_DKService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\TicketsController::delete' => ['privates', '.service_locator.JpDh4Pu', 'get_ServiceLocator_JpDh4PuService', true],
            'App\\Controller\\TicketsController::edit' => ['privates', '.service_locator.JpDh4Pu', 'get_ServiceLocator_JpDh4PuService', true],
            'App\\Controller\\TicketsController::index' => ['privates', '.service_locator.Ew5_NKS', 'get_ServiceLocator_Ew5NKSService', true],
            'App\\Controller\\TicketsController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\TicketsController::show' => ['privates', '.service_locator.f8SUBcK', 'get_ServiceLocator_F8SUBcKService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AnswersController:delete' => ['privates', '.service_locator.4t3QSeC', 'get_ServiceLocator_4t3QSeCService', true],
            'App\\Controller\\AnswersController:edit' => ['privates', '.service_locator.4t3QSeC', 'get_ServiceLocator_4t3QSeCService', true],
            'App\\Controller\\AnswersController:index' => ['privates', '.service_locator.Rl2KN_W', 'get_ServiceLocator_Rl2KNWService', true],
            'App\\Controller\\AnswersController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AnswersController:show' => ['privates', '.service_locator.uUPz.dK', 'get_ServiceLocator_UUPz_DKService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\TicketsController:delete' => ['privates', '.service_locator.JpDh4Pu', 'get_ServiceLocator_JpDh4PuService', true],
            'App\\Controller\\TicketsController:edit' => ['privates', '.service_locator.JpDh4Pu', 'get_ServiceLocator_JpDh4PuService', true],
            'App\\Controller\\TicketsController:index' => ['privates', '.service_locator.Ew5_NKS', 'get_ServiceLocator_Ew5NKSService', true],
            'App\\Controller\\TicketsController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\TicketsController:show' => ['privates', '.service_locator.f8SUBcK', 'get_ServiceLocator_F8SUBcKService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AnswersController::delete' => '?',
            'App\\Controller\\AnswersController::edit' => '?',
            'App\\Controller\\AnswersController::index' => '?',
            'App\\Controller\\AnswersController::new' => '?',
            'App\\Controller\\AnswersController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TicketsController::delete' => '?',
            'App\\Controller\\TicketsController::edit' => '?',
            'App\\Controller\\TicketsController::index' => '?',
            'App\\Controller\\TicketsController::new' => '?',
            'App\\Controller\\TicketsController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AnswersController:delete' => '?',
            'App\\Controller\\AnswersController:edit' => '?',
            'App\\Controller\\AnswersController:index' => '?',
            'App\\Controller\\AnswersController:new' => '?',
            'App\\Controller\\AnswersController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TicketsController:delete' => '?',
            'App\\Controller\\TicketsController:edit' => '?',
            'App\\Controller\\TicketsController:index' => '?',
            'App\\Controller\\TicketsController:new' => '?',
            'App\\Controller\\TicketsController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
