<?php

namespace ContainerO5KUIo8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rl2KNWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rl2KN_W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rl2KN_W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'answersRepository' => ['privates', 'App\\Repository\\AnswersRepository', 'getAnswersRepositoryService', true],
        ], [
            'answersRepository' => 'App\\Repository\\AnswersRepository',
        ]);
    }
}
