<?php

namespace ContainerO5KUIo8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ew5NKSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ew5_NKS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ew5_NKS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ticketsRepository' => ['privates', 'App\\Repository\\TicketsRepository', 'getTicketsRepositoryService', true],
        ], [
            'ticketsRepository' => 'App\\Repository\\TicketsRepository',
        ]);
    }
}
