<?php

namespace ContainerO5KUIo8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F8SUBcKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f8SUBcK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f8SUBcK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ticket' => ['privates', '.errored..service_locator.f8SUBcK.App\\Entity\\Tickets', NULL, 'Cannot autowire service ".service_locator.f8SUBcK": it references class "App\\Entity\\Tickets" but no such service exists.'],
        ], [
            'ticket' => 'App\\Entity\\Tickets',
        ]);
    }
}
