<?php

namespace ContainerO5KUIo8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnswersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4t3QSeC.App\Entity\Answers' shared service.
     *
     * @return \App\Entity\Answers
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4t3QSeC": it references class "App\\Entity\\Answers" but no such service exists.');
    }
}
