<?php

namespace ContainerO5KUIo8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicketsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JpDh4Pu.App\Entity\Tickets' shared service.
     *
     * @return \App\Entity\Tickets
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.JpDh4Pu": it references class "App\\Entity\\Tickets" but no such service exists.');
    }
}
