<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO5KUIo8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO5KUIo8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO5KUIo8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO5KUIo8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO5KUIo8\App_KernelDevDebugContainer([
    'container.build_hash' => 'O5KUIo8',
    'container.build_id' => 'bd95e94d',
    'container.build_time' => 1702905001,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO5KUIo8');
